apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 590183924135.dkr.ecr.us-east-1.amazonaws.com/backend-test
          ports:
            - containerPort: 8080
          env:         
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: mypassword
            - name: DB_NAME
              value: mydatabase
            - name: DB_PORT
              value: "5432"



---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
