name: Frontend job
on:
 push:
   branches: ["main"]
   paths:
    - 'frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add more steps as needed
      - name: Run a script
        run: cd frontend/ && docker build -t my-react-app .
